name: Build PyQt6 application for Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install requirements
        run: |
          pip install pyqt6 pyinstaller

      - name: Build application
        run: |
          .\create_installer.bat
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: qesent_install
          path: qesent_install.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.4
          release_name: qesend v0.4
          draft: false
          prerelease: false
          body: |
            This is a pre-release of qesend.
            It includes the following features:
            - Reads esend.html files
      - name: Publish Binary Release
        id: upload-release-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: qesent_install.exe
          asset_name: qesent_install.exe
          asset_content_type: application/octet-stream

      - name: Get SHA2-256SUMS for qesent_install.exe
        id: sha2_file
        run: echo "sha2_windows=$((Get-FileHash qesent_install.exe -Algorithm SHA256).Hash.ToLower())" >> $GITHUB_OUTPUT
